name: weather_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.6 # https://pub.dev/packages/cupertino_icons
  json_annotation: ^4.8.1 # https://pub.dev/packages/json_annotation
  uuid: ^4.3.3 # https://pub.dev/packages/uuid
  google_fonts: ^6.2.1 # https://pub.dev/packages/google_fonts
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0 # https://pub.dev/packages/flutter_lints
  build_runner: ^2.4.8 # https://pub.dev/packages/build_runner
  json_serializable: ^6.7.1 # https://pub.dev/packages/json_serializable


flutter:


  uses-material-design: true


  assets:
    - assets/images/ 
    - assets/images/clouds/


