name: weather_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
# https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.6
# https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.1 
# https://pub.dev/packages/uuid
  uuid: ^4.3.3 
# https://pub.dev/packages/google_fonts
  google_fonts: ^6.2.1 

  flutter_localizations:
    sdk: flutter
  intl: any
# https://pub.dev/packages/http
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
    # https://pub.dev/packages/flutter_lints
  flutter_lints: ^3.0.0 
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.8 
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.7.1 


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/ 
    - assets/images/clouds/


